server.port: 8888

#spring.cloud.config.server.git.uri=
spring.cloud.config.server:
  git:
    uri: ${HOME}/Documents/IdeaProjects/backend-service-configuration
#    uri: https://github.com/rprzystasz/backend-service-configuration
    default-label: main
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
